server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce_api_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: springstudent
    password: springstudent
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      format_sql: true

jwt:
  expiration: 2592000
  secretKey: TaqlmGv1iEDMRiFp/pHuID1+T84IABfuA0xXh4GhiUI=
  expiration-refresh-token: 60 * 24 * 60 * 60

logging:
  level:
    org:
      springframework.security: DEBUG

#health check
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /api/v1/actuator
      exposure:
        #include: "health"
        include: "health, info"

# swagger-ui custom path
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
  show-actuator: true